/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEPokerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_allCommunityCardsCallback"
      | "_flopCallback"
      | "_riverCallback"
      | "_showdownCallback1Player"
      | "_showdownCallback2Players"
      | "_showdownCallbackMultiplePlayers"
      | "_turnCallback"
      | "addChips"
      | "advanceGame"
      | "allIn"
      | "call"
      | "canAdvanceGame"
      | "check"
      | "createTable"
      | "evaluateHand"
      | "fold"
      | "getBettingInfo"
      | "getCommunityCards"
      | "getCurrentPlayer"
      | "getCurrentStreet"
      | "getMyHoleCards"
      | "getPlayerBettingState"
      | "getPlayerCards"
      | "getPlayers"
      | "getTableState"
      | "getTimeRemaining"
      | "hasPlayerTimedOut"
      | "joinTable"
      | "leaveTable"
      | "protocolId"
      | "raise"
      | "skipTimedOutPlayer"
      | "withdrawChips"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CardsDealt"
      | "CardsRevealed"
      | "DecryptionFulfilled"
      | "FlopDealt"
      | "GameFinished"
      | "GameStarted"
      | "PlayerAllIn"
      | "PlayerCalled"
      | "PlayerChecked"
      | "PlayerFolded"
      | "PlayerJoined"
      | "PlayerKicked"
      | "PlayerLeft"
      | "PlayerRaised"
      | "PlayerTimedOut"
      | "PlayerToppedUp"
      | "PlayerWithdrew"
      | "RiverDealt"
      | "StreetAdvanced"
      | "TableCreated"
      | "TurnDealt"
      | "UncalledBetReturned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "_allCommunityCardsCallback",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "_flopCallback",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "_riverCallback",
    values: [BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "_showdownCallback1Player",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "_showdownCallback2Players",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "_showdownCallbackMultiplePlayers",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_turnCallback",
    values: [BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addChips",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "advanceGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "allIn", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "call", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "canAdvanceGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "check", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "createTable",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "evaluateHand",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "fold", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getBettingInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommunityCards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPlayer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentStreet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyHoleCards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerBettingState",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerCards",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTableState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeRemaining",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPlayerTimedOut",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "joinTable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "leaveTable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raise",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "skipTimedOutPlayer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawChips",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "_allCommunityCardsCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_flopCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_riverCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_showdownCallback1Player",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_showdownCallback2Players",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_showdownCallbackMultiplePlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_turnCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addChips", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "advanceGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "call", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canAdvanceGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "check", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createTable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaluateHand",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBettingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommunityCards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentStreet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyHoleCards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerBettingState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerCards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlayers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTableState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPlayerTimedOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinTable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "leaveTable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "raise", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "skipTimedOutPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawChips",
    data: BytesLike
  ): Result;
}

export namespace CardsDealtEvent {
  export type InputTuple = [tableId: BigNumberish, player: AddressLike];
  export type OutputTuple = [tableId: bigint, player: string];
  export interface OutputObject {
    tableId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CardsRevealedEvent {
  export type InputTuple = [
    tableId: BigNumberish,
    player: AddressLike,
    card1: BigNumberish,
    card2: BigNumberish
  ];
  export type OutputTuple = [
    tableId: bigint,
    player: string,
    card1: bigint,
    card2: bigint
  ];
  export interface OutputObject {
    tableId: bigint;
    player: string;
    card1: bigint;
    card2: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionFulfilledEvent {
  export type InputTuple = [requestID: BigNumberish];
  export type OutputTuple = [requestID: bigint];
  export interface OutputObject {
    requestID: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlopDealtEvent {
  export type InputTuple = [tableId: BigNumberish];
  export type OutputTuple = [tableId: bigint];
  export interface OutputObject {
    tableId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameFinishedEvent {
  export type InputTuple = [tableId: BigNumberish, winner: AddressLike];
  export type OutputTuple = [tableId: bigint, winner: string];
  export interface OutputObject {
    tableId: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameStartedEvent {
  export type InputTuple = [tableId: BigNumberish, round: BigNumberish];
  export type OutputTuple = [tableId: bigint, round: bigint];
  export interface OutputObject {
    tableId: bigint;
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerAllInEvent {
  export type InputTuple = [
    tableId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [tableId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    tableId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerCalledEvent {
  export type InputTuple = [
    tableId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [tableId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    tableId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerCheckedEvent {
  export type InputTuple = [tableId: BigNumberish, player: AddressLike];
  export type OutputTuple = [tableId: bigint, player: string];
  export interface OutputObject {
    tableId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerFoldedEvent {
  export type InputTuple = [tableId: BigNumberish, player: AddressLike];
  export type OutputTuple = [tableId: bigint, player: string];
  export interface OutputObject {
    tableId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerJoinedEvent {
  export type InputTuple = [
    tableId: BigNumberish,
    player: AddressLike,
    buyIn: BigNumberish
  ];
  export type OutputTuple = [tableId: bigint, player: string, buyIn: bigint];
  export interface OutputObject {
    tableId: bigint;
    player: string;
    buyIn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerKickedEvent {
  export type InputTuple = [
    tableId: BigNumberish,
    player: AddressLike,
    refundAmount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    tableId: bigint,
    player: string,
    refundAmount: bigint,
    reason: string
  ];
  export interface OutputObject {
    tableId: bigint;
    player: string;
    refundAmount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerLeftEvent {
  export type InputTuple = [tableId: BigNumberish, player: AddressLike];
  export type OutputTuple = [tableId: bigint, player: string];
  export interface OutputObject {
    tableId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerRaisedEvent {
  export type InputTuple = [
    tableId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [tableId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    tableId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerTimedOutEvent {
  export type InputTuple = [tableId: BigNumberish, player: AddressLike];
  export type OutputTuple = [tableId: bigint, player: string];
  export interface OutputObject {
    tableId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerToppedUpEvent {
  export type InputTuple = [
    tableId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish,
    newTotal: BigNumberish
  ];
  export type OutputTuple = [
    tableId: bigint,
    player: string,
    amount: bigint,
    newTotal: bigint
  ];
  export interface OutputObject {
    tableId: bigint;
    player: string;
    amount: bigint;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerWithdrewEvent {
  export type InputTuple = [
    tableId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [tableId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    tableId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiverDealtEvent {
  export type InputTuple = [tableId: BigNumberish];
  export type OutputTuple = [tableId: bigint];
  export interface OutputObject {
    tableId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreetAdvancedEvent {
  export type InputTuple = [tableId: BigNumberish, newStreet: BigNumberish];
  export type OutputTuple = [tableId: bigint, newStreet: bigint];
  export interface OutputObject {
    tableId: bigint;
    newStreet: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TableCreatedEvent {
  export type InputTuple = [
    tableId: BigNumberish,
    creator: AddressLike,
    minBuyIn: BigNumberish,
    maxPlayers: BigNumberish
  ];
  export type OutputTuple = [
    tableId: bigint,
    creator: string,
    minBuyIn: bigint,
    maxPlayers: bigint
  ];
  export interface OutputObject {
    tableId: bigint;
    creator: string;
    minBuyIn: bigint;
    maxPlayers: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TurnDealtEvent {
  export type InputTuple = [tableId: BigNumberish];
  export type OutputTuple = [tableId: bigint];
  export interface OutputObject {
    tableId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UncalledBetReturnedEvent {
  export type InputTuple = [
    tableId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [tableId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    tableId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEPoker extends BaseContract {
  connect(runner?: ContractRunner | null): FHEPoker;
  waitForDeployment(): Promise<this>;

  interface: FHEPokerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _allCommunityCardsCallback: TypedContractMethod<
    [
      requestId: BigNumberish,
      flop1: BigNumberish,
      flop2: BigNumberish,
      flop3: BigNumberish,
      turn: BigNumberish,
      river: BigNumberish,
      arg6: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  _flopCallback: TypedContractMethod<
    [
      requestId: BigNumberish,
      card1: BigNumberish,
      card2: BigNumberish,
      card3: BigNumberish,
      arg4: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  _riverCallback: TypedContractMethod<
    [requestId: BigNumberish, card: BigNumberish, arg2: BytesLike[]],
    [void],
    "nonpayable"
  >;

  _showdownCallback1Player: TypedContractMethod<
    [
      requestId: BigNumberish,
      card1: BigNumberish,
      card2: BigNumberish,
      arg3: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  _showdownCallback2Players: TypedContractMethod<
    [
      requestId: BigNumberish,
      p1c1: BigNumberish,
      p1c2: BigNumberish,
      p2c1: BigNumberish,
      p2c2: BigNumberish,
      arg5: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  _showdownCallbackMultiplePlayers: TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  _turnCallback: TypedContractMethod<
    [requestId: BigNumberish, card: BigNumberish, arg2: BytesLike[]],
    [void],
    "nonpayable"
  >;

  addChips: TypedContractMethod<[tableId: BigNumberish], [void], "payable">;

  advanceGame: TypedContractMethod<
    [tableId: BigNumberish],
    [void],
    "nonpayable"
  >;

  allIn: TypedContractMethod<[tableId: BigNumberish], [void], "nonpayable">;

  call: TypedContractMethod<[tableId: BigNumberish], [void], "nonpayable">;

  canAdvanceGame: TypedContractMethod<
    [tableId: BigNumberish],
    [boolean],
    "view"
  >;

  check: TypedContractMethod<[tableId: BigNumberish], [void], "nonpayable">;

  createTable: TypedContractMethod<
    [
      minBuyIn: BigNumberish,
      maxPlayers: BigNumberish,
      smallBlind: BigNumberish,
      bigBlind: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  evaluateHand: TypedContractMethod<
    [tableId: BigNumberish, player: AddressLike],
    [
      [bigint, [bigint, bigint, bigint, bigint, bigint]] & {
        rank: bigint;
        tiebreakers: [bigint, bigint, bigint, bigint, bigint];
      }
    ],
    "view"
  >;

  fold: TypedContractMethod<[tableId: BigNumberish], [void], "nonpayable">;

  getBettingInfo: TypedContractMethod<
    [tableId: BigNumberish],
    [
      [bigint, bigint, string, bigint] & {
        pot: bigint;
        currentBet: bigint;
        currentPlayer: string;
        currentPlayerIndex: bigint;
      }
    ],
    "view"
  >;

  getCommunityCards: TypedContractMethod<
    [tableId: BigNumberish],
    [
      [bigint, string, string, string, string, string] & {
        currentStreet: bigint;
        flopCard1: string;
        flopCard2: string;
        flopCard3: string;
        turnCard: string;
        riverCard: string;
      }
    ],
    "view"
  >;

  getCurrentPlayer: TypedContractMethod<
    [tableId: BigNumberish],
    [string],
    "view"
  >;

  getCurrentStreet: TypedContractMethod<
    [tableId: BigNumberish],
    [bigint],
    "view"
  >;

  getMyHoleCards: TypedContractMethod<
    [tableId: BigNumberish],
    [[string, string]],
    "view"
  >;

  getPlayerBettingState: TypedContractMethod<
    [tableId: BigNumberish, player: AddressLike],
    [
      [bigint, bigint, bigint, boolean, boolean, boolean] & {
        chips: bigint;
        currentBet: bigint;
        totalBet: bigint;
        hasFolded: boolean;
        hasActed: boolean;
        isCurrentPlayer: boolean;
      }
    ],
    "view"
  >;

  getPlayerCards: TypedContractMethod<
    [tableId: BigNumberish, player: AddressLike],
    [[bigint, bigint] & { card1: bigint; card2: bigint }],
    "view"
  >;

  getPlayers: TypedContractMethod<[tableId: BigNumberish], [string[]], "view">;

  getTableState: TypedContractMethod<
    [tableId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        state: bigint;
        numPlayers: bigint;
        maxPlayers: bigint;
        minBuyIn: bigint;
        currentRound: bigint;
        isSeated: boolean;
        turnStartTime: bigint;
        playerActionTimeout: bigint;
      }
    ],
    "view"
  >;

  getTimeRemaining: TypedContractMethod<
    [tableId: BigNumberish],
    [bigint],
    "view"
  >;

  hasPlayerTimedOut: TypedContractMethod<
    [tableId: BigNumberish],
    [boolean],
    "view"
  >;

  joinTable: TypedContractMethod<[tableId: BigNumberish], [void], "payable">;

  leaveTable: TypedContractMethod<
    [tableId: BigNumberish],
    [void],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  raise: TypedContractMethod<
    [tableId: BigNumberish, raiseAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  skipTimedOutPlayer: TypedContractMethod<
    [tableId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawChips: TypedContractMethod<
    [tableId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_allCommunityCardsCallback"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      flop1: BigNumberish,
      flop2: BigNumberish,
      flop3: BigNumberish,
      turn: BigNumberish,
      river: BigNumberish,
      arg6: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_flopCallback"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      card1: BigNumberish,
      card2: BigNumberish,
      card3: BigNumberish,
      arg4: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_riverCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, card: BigNumberish, arg2: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_showdownCallback1Player"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      card1: BigNumberish,
      card2: BigNumberish,
      arg3: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_showdownCallback2Players"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      p1c1: BigNumberish,
      p1c2: BigNumberish,
      p2c1: BigNumberish,
      p2c2: BigNumberish,
      arg5: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_showdownCallbackMultiplePlayers"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_turnCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, card: BigNumberish, arg2: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addChips"
  ): TypedContractMethod<[tableId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "advanceGame"
  ): TypedContractMethod<[tableId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allIn"
  ): TypedContractMethod<[tableId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "call"
  ): TypedContractMethod<[tableId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canAdvanceGame"
  ): TypedContractMethod<[tableId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "check"
  ): TypedContractMethod<[tableId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTable"
  ): TypedContractMethod<
    [
      minBuyIn: BigNumberish,
      maxPlayers: BigNumberish,
      smallBlind: BigNumberish,
      bigBlind: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "evaluateHand"
  ): TypedContractMethod<
    [tableId: BigNumberish, player: AddressLike],
    [
      [bigint, [bigint, bigint, bigint, bigint, bigint]] & {
        rank: bigint;
        tiebreakers: [bigint, bigint, bigint, bigint, bigint];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fold"
  ): TypedContractMethod<[tableId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBettingInfo"
  ): TypedContractMethod<
    [tableId: BigNumberish],
    [
      [bigint, bigint, string, bigint] & {
        pot: bigint;
        currentBet: bigint;
        currentPlayer: string;
        currentPlayerIndex: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCommunityCards"
  ): TypedContractMethod<
    [tableId: BigNumberish],
    [
      [bigint, string, string, string, string, string] & {
        currentStreet: bigint;
        flopCard1: string;
        flopCard2: string;
        flopCard3: string;
        turnCard: string;
        riverCard: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentPlayer"
  ): TypedContractMethod<[tableId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentStreet"
  ): TypedContractMethod<[tableId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyHoleCards"
  ): TypedContractMethod<[tableId: BigNumberish], [[string, string]], "view">;
  getFunction(
    nameOrSignature: "getPlayerBettingState"
  ): TypedContractMethod<
    [tableId: BigNumberish, player: AddressLike],
    [
      [bigint, bigint, bigint, boolean, boolean, boolean] & {
        chips: bigint;
        currentBet: bigint;
        totalBet: bigint;
        hasFolded: boolean;
        hasActed: boolean;
        isCurrentPlayer: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerCards"
  ): TypedContractMethod<
    [tableId: BigNumberish, player: AddressLike],
    [[bigint, bigint] & { card1: bigint; card2: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayers"
  ): TypedContractMethod<[tableId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTableState"
  ): TypedContractMethod<
    [tableId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        state: bigint;
        numPlayers: bigint;
        maxPlayers: bigint;
        minBuyIn: bigint;
        currentRound: bigint;
        isSeated: boolean;
        turnStartTime: bigint;
        playerActionTimeout: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTimeRemaining"
  ): TypedContractMethod<[tableId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasPlayerTimedOut"
  ): TypedContractMethod<[tableId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "joinTable"
  ): TypedContractMethod<[tableId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "leaveTable"
  ): TypedContractMethod<[tableId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raise"
  ): TypedContractMethod<
    [tableId: BigNumberish, raiseAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "skipTimedOutPlayer"
  ): TypedContractMethod<[tableId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawChips"
  ): TypedContractMethod<
    [tableId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CardsDealt"
  ): TypedContractEvent<
    CardsDealtEvent.InputTuple,
    CardsDealtEvent.OutputTuple,
    CardsDealtEvent.OutputObject
  >;
  getEvent(
    key: "CardsRevealed"
  ): TypedContractEvent<
    CardsRevealedEvent.InputTuple,
    CardsRevealedEvent.OutputTuple,
    CardsRevealedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionFulfilled"
  ): TypedContractEvent<
    DecryptionFulfilledEvent.InputTuple,
    DecryptionFulfilledEvent.OutputTuple,
    DecryptionFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "FlopDealt"
  ): TypedContractEvent<
    FlopDealtEvent.InputTuple,
    FlopDealtEvent.OutputTuple,
    FlopDealtEvent.OutputObject
  >;
  getEvent(
    key: "GameFinished"
  ): TypedContractEvent<
    GameFinishedEvent.InputTuple,
    GameFinishedEvent.OutputTuple,
    GameFinishedEvent.OutputObject
  >;
  getEvent(
    key: "GameStarted"
  ): TypedContractEvent<
    GameStartedEvent.InputTuple,
    GameStartedEvent.OutputTuple,
    GameStartedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerAllIn"
  ): TypedContractEvent<
    PlayerAllInEvent.InputTuple,
    PlayerAllInEvent.OutputTuple,
    PlayerAllInEvent.OutputObject
  >;
  getEvent(
    key: "PlayerCalled"
  ): TypedContractEvent<
    PlayerCalledEvent.InputTuple,
    PlayerCalledEvent.OutputTuple,
    PlayerCalledEvent.OutputObject
  >;
  getEvent(
    key: "PlayerChecked"
  ): TypedContractEvent<
    PlayerCheckedEvent.InputTuple,
    PlayerCheckedEvent.OutputTuple,
    PlayerCheckedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerFolded"
  ): TypedContractEvent<
    PlayerFoldedEvent.InputTuple,
    PlayerFoldedEvent.OutputTuple,
    PlayerFoldedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerJoined"
  ): TypedContractEvent<
    PlayerJoinedEvent.InputTuple,
    PlayerJoinedEvent.OutputTuple,
    PlayerJoinedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerKicked"
  ): TypedContractEvent<
    PlayerKickedEvent.InputTuple,
    PlayerKickedEvent.OutputTuple,
    PlayerKickedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerLeft"
  ): TypedContractEvent<
    PlayerLeftEvent.InputTuple,
    PlayerLeftEvent.OutputTuple,
    PlayerLeftEvent.OutputObject
  >;
  getEvent(
    key: "PlayerRaised"
  ): TypedContractEvent<
    PlayerRaisedEvent.InputTuple,
    PlayerRaisedEvent.OutputTuple,
    PlayerRaisedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerTimedOut"
  ): TypedContractEvent<
    PlayerTimedOutEvent.InputTuple,
    PlayerTimedOutEvent.OutputTuple,
    PlayerTimedOutEvent.OutputObject
  >;
  getEvent(
    key: "PlayerToppedUp"
  ): TypedContractEvent<
    PlayerToppedUpEvent.InputTuple,
    PlayerToppedUpEvent.OutputTuple,
    PlayerToppedUpEvent.OutputObject
  >;
  getEvent(
    key: "PlayerWithdrew"
  ): TypedContractEvent<
    PlayerWithdrewEvent.InputTuple,
    PlayerWithdrewEvent.OutputTuple,
    PlayerWithdrewEvent.OutputObject
  >;
  getEvent(
    key: "RiverDealt"
  ): TypedContractEvent<
    RiverDealtEvent.InputTuple,
    RiverDealtEvent.OutputTuple,
    RiverDealtEvent.OutputObject
  >;
  getEvent(
    key: "StreetAdvanced"
  ): TypedContractEvent<
    StreetAdvancedEvent.InputTuple,
    StreetAdvancedEvent.OutputTuple,
    StreetAdvancedEvent.OutputObject
  >;
  getEvent(
    key: "TableCreated"
  ): TypedContractEvent<
    TableCreatedEvent.InputTuple,
    TableCreatedEvent.OutputTuple,
    TableCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TurnDealt"
  ): TypedContractEvent<
    TurnDealtEvent.InputTuple,
    TurnDealtEvent.OutputTuple,
    TurnDealtEvent.OutputObject
  >;
  getEvent(
    key: "UncalledBetReturned"
  ): TypedContractEvent<
    UncalledBetReturnedEvent.InputTuple,
    UncalledBetReturnedEvent.OutputTuple,
    UncalledBetReturnedEvent.OutputObject
  >;

  filters: {
    "CardsDealt(uint256,address)": TypedContractEvent<
      CardsDealtEvent.InputTuple,
      CardsDealtEvent.OutputTuple,
      CardsDealtEvent.OutputObject
    >;
    CardsDealt: TypedContractEvent<
      CardsDealtEvent.InputTuple,
      CardsDealtEvent.OutputTuple,
      CardsDealtEvent.OutputObject
    >;

    "CardsRevealed(uint256,address,uint32,uint32)": TypedContractEvent<
      CardsRevealedEvent.InputTuple,
      CardsRevealedEvent.OutputTuple,
      CardsRevealedEvent.OutputObject
    >;
    CardsRevealed: TypedContractEvent<
      CardsRevealedEvent.InputTuple,
      CardsRevealedEvent.OutputTuple,
      CardsRevealedEvent.OutputObject
    >;

    "DecryptionFulfilled(uint256)": TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;
    DecryptionFulfilled: TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;

    "FlopDealt(uint256)": TypedContractEvent<
      FlopDealtEvent.InputTuple,
      FlopDealtEvent.OutputTuple,
      FlopDealtEvent.OutputObject
    >;
    FlopDealt: TypedContractEvent<
      FlopDealtEvent.InputTuple,
      FlopDealtEvent.OutputTuple,
      FlopDealtEvent.OutputObject
    >;

    "GameFinished(uint256,address)": TypedContractEvent<
      GameFinishedEvent.InputTuple,
      GameFinishedEvent.OutputTuple,
      GameFinishedEvent.OutputObject
    >;
    GameFinished: TypedContractEvent<
      GameFinishedEvent.InputTuple,
      GameFinishedEvent.OutputTuple,
      GameFinishedEvent.OutputObject
    >;

    "GameStarted(uint256,uint256)": TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;
    GameStarted: TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;

    "PlayerAllIn(uint256,address,uint256)": TypedContractEvent<
      PlayerAllInEvent.InputTuple,
      PlayerAllInEvent.OutputTuple,
      PlayerAllInEvent.OutputObject
    >;
    PlayerAllIn: TypedContractEvent<
      PlayerAllInEvent.InputTuple,
      PlayerAllInEvent.OutputTuple,
      PlayerAllInEvent.OutputObject
    >;

    "PlayerCalled(uint256,address,uint256)": TypedContractEvent<
      PlayerCalledEvent.InputTuple,
      PlayerCalledEvent.OutputTuple,
      PlayerCalledEvent.OutputObject
    >;
    PlayerCalled: TypedContractEvent<
      PlayerCalledEvent.InputTuple,
      PlayerCalledEvent.OutputTuple,
      PlayerCalledEvent.OutputObject
    >;

    "PlayerChecked(uint256,address)": TypedContractEvent<
      PlayerCheckedEvent.InputTuple,
      PlayerCheckedEvent.OutputTuple,
      PlayerCheckedEvent.OutputObject
    >;
    PlayerChecked: TypedContractEvent<
      PlayerCheckedEvent.InputTuple,
      PlayerCheckedEvent.OutputTuple,
      PlayerCheckedEvent.OutputObject
    >;

    "PlayerFolded(uint256,address)": TypedContractEvent<
      PlayerFoldedEvent.InputTuple,
      PlayerFoldedEvent.OutputTuple,
      PlayerFoldedEvent.OutputObject
    >;
    PlayerFolded: TypedContractEvent<
      PlayerFoldedEvent.InputTuple,
      PlayerFoldedEvent.OutputTuple,
      PlayerFoldedEvent.OutputObject
    >;

    "PlayerJoined(uint256,address,uint256)": TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
    PlayerJoined: TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;

    "PlayerKicked(uint256,address,uint256,string)": TypedContractEvent<
      PlayerKickedEvent.InputTuple,
      PlayerKickedEvent.OutputTuple,
      PlayerKickedEvent.OutputObject
    >;
    PlayerKicked: TypedContractEvent<
      PlayerKickedEvent.InputTuple,
      PlayerKickedEvent.OutputTuple,
      PlayerKickedEvent.OutputObject
    >;

    "PlayerLeft(uint256,address)": TypedContractEvent<
      PlayerLeftEvent.InputTuple,
      PlayerLeftEvent.OutputTuple,
      PlayerLeftEvent.OutputObject
    >;
    PlayerLeft: TypedContractEvent<
      PlayerLeftEvent.InputTuple,
      PlayerLeftEvent.OutputTuple,
      PlayerLeftEvent.OutputObject
    >;

    "PlayerRaised(uint256,address,uint256)": TypedContractEvent<
      PlayerRaisedEvent.InputTuple,
      PlayerRaisedEvent.OutputTuple,
      PlayerRaisedEvent.OutputObject
    >;
    PlayerRaised: TypedContractEvent<
      PlayerRaisedEvent.InputTuple,
      PlayerRaisedEvent.OutputTuple,
      PlayerRaisedEvent.OutputObject
    >;

    "PlayerTimedOut(uint256,address)": TypedContractEvent<
      PlayerTimedOutEvent.InputTuple,
      PlayerTimedOutEvent.OutputTuple,
      PlayerTimedOutEvent.OutputObject
    >;
    PlayerTimedOut: TypedContractEvent<
      PlayerTimedOutEvent.InputTuple,
      PlayerTimedOutEvent.OutputTuple,
      PlayerTimedOutEvent.OutputObject
    >;

    "PlayerToppedUp(uint256,address,uint256,uint256)": TypedContractEvent<
      PlayerToppedUpEvent.InputTuple,
      PlayerToppedUpEvent.OutputTuple,
      PlayerToppedUpEvent.OutputObject
    >;
    PlayerToppedUp: TypedContractEvent<
      PlayerToppedUpEvent.InputTuple,
      PlayerToppedUpEvent.OutputTuple,
      PlayerToppedUpEvent.OutputObject
    >;

    "PlayerWithdrew(uint256,address,uint256)": TypedContractEvent<
      PlayerWithdrewEvent.InputTuple,
      PlayerWithdrewEvent.OutputTuple,
      PlayerWithdrewEvent.OutputObject
    >;
    PlayerWithdrew: TypedContractEvent<
      PlayerWithdrewEvent.InputTuple,
      PlayerWithdrewEvent.OutputTuple,
      PlayerWithdrewEvent.OutputObject
    >;

    "RiverDealt(uint256)": TypedContractEvent<
      RiverDealtEvent.InputTuple,
      RiverDealtEvent.OutputTuple,
      RiverDealtEvent.OutputObject
    >;
    RiverDealt: TypedContractEvent<
      RiverDealtEvent.InputTuple,
      RiverDealtEvent.OutputTuple,
      RiverDealtEvent.OutputObject
    >;

    "StreetAdvanced(uint256,uint8)": TypedContractEvent<
      StreetAdvancedEvent.InputTuple,
      StreetAdvancedEvent.OutputTuple,
      StreetAdvancedEvent.OutputObject
    >;
    StreetAdvanced: TypedContractEvent<
      StreetAdvancedEvent.InputTuple,
      StreetAdvancedEvent.OutputTuple,
      StreetAdvancedEvent.OutputObject
    >;

    "TableCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      TableCreatedEvent.InputTuple,
      TableCreatedEvent.OutputTuple,
      TableCreatedEvent.OutputObject
    >;
    TableCreated: TypedContractEvent<
      TableCreatedEvent.InputTuple,
      TableCreatedEvent.OutputTuple,
      TableCreatedEvent.OutputObject
    >;

    "TurnDealt(uint256)": TypedContractEvent<
      TurnDealtEvent.InputTuple,
      TurnDealtEvent.OutputTuple,
      TurnDealtEvent.OutputObject
    >;
    TurnDealt: TypedContractEvent<
      TurnDealtEvent.InputTuple,
      TurnDealtEvent.OutputTuple,
      TurnDealtEvent.OutputObject
    >;

    "UncalledBetReturned(uint256,address,uint256)": TypedContractEvent<
      UncalledBetReturnedEvent.InputTuple,
      UncalledBetReturnedEvent.OutputTuple,
      UncalledBetReturnedEvent.OutputObject
    >;
    UncalledBetReturned: TypedContractEvent<
      UncalledBetReturnedEvent.InputTuple,
      UncalledBetReturnedEvent.OutputTuple,
      UncalledBetReturnedEvent.OutputObject
    >;
  };
}
